; File autogenerated by build-flavored-queries.py; do not edit

; This file specifies how matched syntax patterns should be highlighted

[
  "export"
  "import"
] @keyword.import

"mod" @module

[
  "alias"
  "set"
  "shell"
] @keyword

[
  "if"
  "else"
] @keyword.conditional

; Variables

(value
  (identifier) @variable)

(alias
  left: (identifier) @variable)

(assignment
  left: (identifier) @variable)

; Functions

(recipe_header
  name: (identifier) @function)

(dependency
  name: (target) @function.call)

(dependency_expression
  name: (target) @function.call)

(function_call
  name: (identifier) @function.call)

(assert) @function.call

; Parameters

(parameter
  name: (identifier) @variable.parameter)

; Namespaces

(module
  name: (identifier) @module)

; Operators

[
  ":="
  "=="
  "!="
  "=~"
  "="
  "$"
  "*"
  "+"
  "&&"
  "||"
  "/"
  ":"
  "@"
  "-"
  "?"
  "@-"
  "@?"
  "-@"
  "-?"
  "?@"
  "?-"
  "@-?"
  "@?-"
  "-@?"
  "-?@"
  "?@-"
  "?-@"
] @operator

; Punctuation

"," @punctuation.delimiter

[
  "{"
  "}"
  "["
  "]"
  "("
  ")"
  "{{"
  "}}"
] @punctuation.bracket

[ "`" "```" ] @punctuation.special

; Literals

(boolean) @boolean

[
  (string)
  (external_command)
] @string

(escape_sequence) @string.escape

; Comments

(comment) @spell @comment

(shebang) @keyword.directive

; highlight known settings (filtering does not always work)
(setting
  left: [
    "allow-duplicate-recipes"
    "allow-duplicate-variables"
    "default-list"
    "default-script"
    "dotenv-command"
    "dotenv-filename"
    "dotenv-load"
    "dotenv-override"
    "dotenv-path"
    "dotenv-required"
    "export"
    "fallback"
    "guards"
    "ignore-comments"
    "indentation"
    "lazy"
    "lists"
    "minimum-version"
    "no-cd"
    "no-exit-message"
    "positional-arguments"
    "quiet"
    "script-interpreter"
    "shell"
    "tempdir"
    "unstable"
    "windows-powershell"
    "windows-shell"
    "working-directory"
  ] @keyword)

; highlight known attributes (filtering does not always work)
(attribute
  (identifier) @attribute
  (#any-of? @attribute
    "android"
    "arg"
    "confirm"
    "default"
    "dragonfly"
    "doc"
    "env"
    "extension"
    "exit-message"
    "freebsd"
    "group"
    "linux"
    "macos"
    "metadata"
    "netbsd"
    "no-cd"
    "no-exit-message"
    "no-quiet"
    "openbsd"
    "parallel"
    "positional-arguments"
    "private"
    "script"
    "unix"
    "windows"
    "working-directory"))

; Numbers are part of the syntax tree, even if disallowed
(numeric_error) @error
