; File autogenerated by build-flavored-queries.py; do not edit

; This file tells us about the scope of variables so e.g. local
; variables override global functions with the same name

; Scope

(recipe) @local.scope

; Definitions

(alias
  left: (identifier) @local.definition.var)

(assignment
  left: (identifier) @local.definition.var)

(module
  name: (identifier) @local.definition.namespace)

(parameter
  name: (identifier) @local.definition.var)

(recipe_header
  name: (identifier) @local.definition.function)

(function
  name: (identifier) @local.definition.function)

; References

(alias
  right: (target) @local.reference)

(function_call
  name: (identifier) @local.reference)

(dependency
  name: (target) @local.reference)

(dependency_expression
  name: (target) @local.reference)

(value
  (identifier) @local.reference)
