; File autogenerated by build-flavored-queries.py; do not edit

; This file specifies how matched syntax patterns should be highlighted

[
  "export"
  "import"
] @keyword.control.import

"mod" @keyword.directive

[
  "alias"
  "set"
  "shell"
] @keyword

[
  "if"
  "else"
] @keyword.control.conditional

; Variables

(value
  (identifier) @variable)

(value
  (identifier) @constant.builtin
  (#any-of? @constant.builtin
    "HEX"
    "HEXLOWER"
    "HEXUPPER"
    "PATH_SEP"
    "PATH_VAR_SEP"
    "CLEAR"
    "NORMAL"
    "BOLD"
    "ITALIC"
    "UNDERLINE"
    "INVERT"
    "HIDE"
    "STRIKETHROUGH"
    "BLACK"
    "RED"
    "GREEN"
    "YELLOW"
    "BLUE"
    "MAGENTA"
    "CYAN"
    "WHITE"
    "BG_BLACK"
    "BG_RED"
    "BG_GREEN"
    "BG_YELLOW"
    "BG_BLUE"
    "BG_MAGENTA"
    "BG_CYAN"
    "BG_WHITE"))

(alias
  left: (identifier) @variable)

(assignment
  left: (identifier) @variable)

; Functions

(recipe_header
  name: (identifier) @function)

(dependency
  name: (target) @function)

(dependency_expression
  name: (target) @function)

(assert) @function @function.builtin

(function
  name: (identifier) @function
  parameters: (function_parameters
    (identifier) @variable.parameter))

(function_call
  name: (identifier) @function)

(function_call
  name: (identifier) @function.builtin
  (#any-of? @function.builtin
    "arch"
    "num_cpus"
    "os"
    "os_family"
    "shell"
    "env"
    "env_var"
    "env_var_or_default"
    "require"
    "which"
    "is_dependency"
    "invocation_directory"
    "invocation_dir"
    "invocation_directory_native"
    "justfile"
    "justfile_directory"
    "justfile_dir"
    "source_file"
    "source_directory"
    "source_dir"
    "module_file"
    "module_directory"
    "module_dir"
    "just_executable"
    "just_pid"
    "append"
    "prepend"
    "encode_uri_components"
    "quote"
    "replace"
    "replace_regex"
    "trim"
    "trim_end"
    "trim_end_match"
    "trim_end_matches"
    "trim_start"
    "trim_start_match"
    "trim_start_matches"
    "capitalize"
    "kebabcase"
    "lowercamelcase"
    "lowercase"
    "shoutykebabcase"
    "shoutysnakecase"
    "snakecase"
    "titlecase"
    "uppercamelcase"
    "uppercase"
    "absolute_path"
    "canonicalize"
    "extension"
    "file_name"
    "file_stem"
    "parent_directory"
    "parent_dir"
    "without_extension"
    "clean"
    "join"
    "path_exists"
    "read"
    "error"
    "blake3"
    "blake3_file"
    "sha256"
    "sha256_file"
    "uuid"
    "choose"
    "datetime"
    "datetime_utc"
    "semver_matches"
    "style"
    "cache_directory"
    "cache_dir"
    "config_directory"
    "config_dir"
    "config_local_directory"
    "config_local_dir"
    "data_directory"
    "data_dir"
    "data_local_directory"
    "data_local_dir"
    "executable_directory"
    "executable_dir"
    "home_directory"
    "home_dir"
    "runtime_directory"
    "runtime_dir"))

; Parameters

(parameter
  name: (identifier) @variable.parameter)

; Namespaces

(module
  name: (identifier) @namespace)

; Operators

[
  ":="
  "?"
  "=="
  "!="
  "=~"
  "@"
  "="
  "$"
  "*"
  "+"
  "&&"
  "||"
  "@-"
  "-@"
  "-"
  "/"
  ":"
] @operator

; Punctuation

"," @punctuation.delimiter


[
  "{"
  "}"
  "["
  "]"
  "("
  ")"
  "{{"
  "}}"
] @punctuation.bracket

[ "`" "```" ] @punctuation.special

; Literals

(boolean) @constant.builtin.boolean

[
  (string)
  (external_command)
] @string

(escape_sequence) @constant.character.escape

; Comments

(comment) @comment.line

(shebang) @keyword.directive

; highlight known settings (filtering does not always work)
(setting
  left: [
    "allow-duplicate-recipes"
    "allow-duplicate-variables"
    "dotenv-filename"
    "dotenv-load"
    "dotenv-path"
    "dotenv-required"
    "export"
    "fallback"
    "ignore-comments"
    "positional-arguments"
    "script-interpreter"
    "quiet"
    "shell"
    "tempdir"
    "unstable"
    "windows-powershell"
    "windows-shell"
    "working-directory"
  ] @keyword)

; highlight known attributes (filtering does not always work)
(attribute
  (identifier) @attribute
  (#any-of? @attribute
    "arg"
    "confirm"
    "default"
    "doc"
    "dragonfly"
    "env"
    "extension"
    "freebsd"
    "group"
    "linux"
    "macos"
    "metadata"
    "netbsd"
    "no-cd"
    "no-exit-message"
    "no-quiet"
    "openbsd"
    "parallel"
    "positional-arguments"
    "private"
    "script"
    "unix"
    "windows"
    "working-directory"))

; Numbers are part of the syntax tree, even if disallowed
(numeric_error) @error
